server:
  port: 8080

spring:
  application:
    name: spring-project

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i12c108.p.ssafy.io:3306/test
    username: ssafy
    password: C108bob!!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
