server:
  port: 8080

spring:
  application:
    name: spring-project

  profiles:
    include: aws

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: 43.202.60.173
      port: 6379

#  config:
#    import: optional:classpath:jwt-config.yml

jwt:
  secretKey: MzY4IHN1cGVyIHNlY3JldCBrZXkgdGhhdCBpcyBhd2Vzb21l...
  access:
    expiration: 30
  refresh:
    expiration-hours: 864000
  issuer: BobIssue

logging:
  file:
    name: logs/application.log
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.security: DEBUG
