server:
  port: 8080

spring:
  application:
    name: spring-project

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  profiles:
    include: aws

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i12c108.p.ssafy.io:3306/test
    username: ssafy
    password: C108bob!!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: 43.202.60.173
      port: 6379
    mongodb:
      host: 43.202.60.173
      port: 27017
      username: bobissue
      password: C108bob!!
      authentication-database: admin  # 인증을 사용할 경우 추가
      database: bobChat

#    elasticsearch:
#      uris: http://bobissue.store:9200
#      username: elastic
#      password: cMvp=DUQcyc9NH5E*1h5
#      # ssl:
#      #   enabled: true
#      #   trust-store: classpath:truststore.jks
#      #   trust-store-password: truststore-password

  elasticsearch:
    uris: http://bobissue.store:9200
    username: elastic
    password: "ok=Z+-QeSD9vAvWvY8KV"

#    config:
#      import: optional:classpath:elasticsearch-config.yml

#
#  elasticsearch:
#    rest:
#      uris: http://bobissue.store:9200
#      read-timeout: 5s
#    cluster-name: docker-cluster
#    cluster-nodes: bobissue.store:9200
#    http.cors.enabled: true
#    http.cors.allow-origin: "*"
#
#  config:
#    import: optional:classpath:elasticsearch-config.yml



  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8f481a81b837b3c5bd608b855e404e32
            client-secret: ig7qbRV0aeZzNxKWpMeR3SV7lhv4iYsA
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://bobissue.duckdns.org:8082/login/oauth2/code/kakao
            scope: profile_nickname, account_email

#            naver:
#              client-id: wn7wFynGCr6frnqw67zw
#              client-secret: sZ18YwI4lu
#              client-name: Naver
#              client-authentication-method: POST
#              authorization-grant-type: authorization_code
#              redirect-uri: http://bobissue.duckdns.org/api/social

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#            naver:
#              authorization-uri: https://nid.naver.com/oauth2.0/authorize
#              token_uri: https://nid.naver.com/oauth2.0/token
#              user-info-uri: https://openapi.naver.com/v1/nid/me
#              user_name_attribute: response

#  config:
#    import: optional:classpath:jwt-config.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssaminute@gmail.com
    password: caqq iywv mhqo yymc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  task:
    scheduling:
      enabled: true

jwt:
  secretKey: MzY4IHN1cGVyIHNlY3JldCBrZXkgdGhhdCBpcyBhd2Vzb21l...
  access:
    expiration: 6000
  refresh:
    expiration-hours: 24
  issuer: BobIssue


system:
  properties:
    javax.net.ssl.trustStore: "/etc/ssl/certs/java/cacerts"
    javax.net.ssl.trustStorePassword: "changeit"




